# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate netmap_sys

Name:           rust-%{crate}
Version:        0.1.3
Release:        1%{?dist}
Summary:        Bindings to netmap - the fast packet I/O framework

# Upstream license specification: BSD-2-Clause
License:        BSD
URL:            https://crates.io/crates/netmap_sys
Source:         %{crates_source}
Patch0:		update-build-rs.patch
Patch1:		replace-gcc-with-cc.patch	

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
BuildRequires:  (crate(cc/default) >= 1.0.35 with crate(cc/default) < 1.0.36)
BuildRequires:  (crate(libc/default) >= 0.2.0 with crate(libc/default) < 0.3.0)

%global _description \
Bindings to netmap - the fast packet I/O framework.

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%doc README.md
%{cargo_registry}/%{crate}-%{version}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+netmap_with_libs-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+netmap_with_libs-devel %{_description}

This package contains library source intended for building other packages
which use "netmap_with_libs" feature of "%{crate}" crate.

%files       -n %{name}+netmap_with_libs-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Wed Apr 10 2019 Sayan Chowdhury <sayanchowdhury@fedoraproject.org> - 0.1.3-1
- Initial package
